.\" Hey, EMACS: -*- nroff -*-
.\" nano-tiny.1 is copyright 2002 by
.\" Jordi Mallach <jordi@debian.org>
.\"
.\" (c) 2003 Jean-Philippe Guérard <jean-philippe.guerard@corbeaunoir.org>
.\" pour l'adaptation française
.\"
.\" This is free documentation, see the latest version of the GNU General
.\" Public License for copying conditions. There is NO warranty.
.\"
.\" Ce document est libre. Reportez-vous à la dernière version de la
.\" licence publique générale GNU (GNU GPL) pour connaître ses 
.\" conditions d'utilisation. AUCUNE garantie n'est offerte.
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH NANO-TINY 1 "20 février 2002 (v.f. du 25 août 2003)"
.\" Please adjust this date whenever revising the manpage.
.\" Merci de modifier ces dates à chaque mise à jour de cette page.
.\"

.SH NOM
nano-tiny \- NAno un NOuvel éditeur, un clone libre et amélioré de Pico

.SH SYNOPSIS
.B nano-tiny
.RI [options]\ [+LIGNE] " fichier"
.br

.SH DESCRIPTION
Cette page de manuel décrit brièvement la commande \fBnano-tiny\fP.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invoke bold face and italics, 
.\" respectively.
\fBnano\fP est un petit éditeur sympathique et libre, qui vise à remplacer
Pico, l'éditeur par défaut du paquet non-libre Pine. \fBnano\fP ne se 
contentant pas de copier l'interface et l'ergonomie de Pico, il offre 
également certaines fonctionnalités manquantes (ou désactivées par 
défaut) de Pico. Ces fonctionnalités sont, par exemple, les fonctions de 
recherche et de remplacement, et la possibilité de sauter directement à 
un numéro de ligne.

.B nano-tiny
est une version spéciale de nano, réduite au minimum, et destinée aux 
disquettes de démarrage Debian ou aux disques de secours.

Contrairement à la version complète de \fBnano\fP, cette version n'est 
disponible qu'en langue anglaise.

.SH OPTIONS
.TP
.B \-V (\-\-version)
Affiche le numéro de version et l'auteur.
.TP
.B \-h (\-\-help)
Affiche le résumé des options disponibles en ligne de commande.

.SH BOGUES
Merci de nous faire parvenir vos commentaires et de nous signaler les 
bogues, en écrivant, en anglais, à
.BR nano@nano-editor.org .

N'hésitez pas à faire parvenir vos suggestions et commentaires relatifs 
à la version française de \fBnano\fP à
.BR jean-philippe.guerard@corbeaunoir.org .

La liste de discussion anglophone \fBnano\fP est disponible via
.BR nano-devel@gnu.org .
Pour vous abonner, envoyez un courrier électronique à
.BR nano-devel-request@gnu.org ,
ayant pour objet «\ subscribe\ ».

.SH SITE INTERNET
http://www.nano-editor.org/

.SH AUTEUR
Chris Allegretta <chrisa@asty.org> et d'autres (voir les fichiers 
\fIAUTHORS\fP et \fITHANKS\fP pour plus d'information). Cette page de 
manuel a été initialement rédigée par Jordi Mallach 
<jordi@sindominio.net> pour le système GNU Debian (mais elle peut être 
utilisée par d'autres).

.SH TRADUCTION
Jean-Philippe Guérard <jean-philippe.guerard@corbeaunoir.org>, 2003.
